server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    # password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug


bloomFilter:
  # 是否启用布隆过滤器
  bloomFilterFlag: true
  # 布隆过滤器的初始大小
  MIN_EXPECTED_INSERTIONS: 8
  # 布隆过滤器的错误率
  bloomFilterErrorRate: 0.01
  # 布隆过滤器的最大使用率
  maximumUtilization: 0.90
  # 布隆过滤器的最小使用率
  minimumUtilization: 0.40
  # 布隆过滤器的初始序列号
  RBloomFilterSequence: 1
